apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-gitops
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-openshift-gitops-001 
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/
    repoURL: https://github.com/giulianoquites/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
